
services:
  mongodb:
    image: mongo:6.0
    container_name: battery_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"        # MQTT TCP
      # - "9001:9001"      # (opsiyonel) WebSocket
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yed_backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: battery_db    
      MQTT_HOST: mqtt
      MQTT_PORT: "1883"
    depends_on:
      - mongodb
      - mqtt
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yed_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"  # Nginx üzerinde servis
    environment:
      - VITE_API_BASE=https://<senin-backend-ngrok-urlin>

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    depends_on:
      - backend
      - mqtt
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    ports:
      - "4040:4040"  # ngrok Dashboard
